version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 5005:5005
    depends_on:
      - db
    networks:
      - network_prueba
  db:
    image: postgres
    environment:
      - POSTGRES_USER=prueba
      - POSTGRES_PASSWORD=prueba
      - POSTGRES_DB=prueba
    ports:
      - 5435:5435
    networks:
      - network_prueba

networks:
  network_prueba: