version: '3.8'

services:
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=prueba
      - DB_USER=prueba
      - DB_PASSWORD=prueba
    depends_on:
      - postgres
    networks:
      - network_prueba
  postgres:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=prueba
      - POSTGRES_USER=prueba
      - POSTGRES_PASSWORD=prueba
    networks:
      - network_prueba

networks:
  network_prueba: